# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'first player to move'), ('S', 'second to move'), ('w', 'first player wins'), ('l', 'second player wins'), ('d', 'draw')], default='F', max_length=1),
        ),
    ]
